name: Testing - main

on: [push, pull_request]

jobs:
  build:

    strategy:
      max-parallel: 20
      matrix:
        include:
          - os: macos-latest
            python-version: 3.8
          - os: windows-latest
            python-version: 3.8

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set Mac Paths
      if: matrix.os == 'macos-latest'
      run: |
        # Note that this is the way to update env variables in a way that persist for the entire job.
        for pkg in `ls cmd_line`; do echo "`pwd`/cmd_line/$pkg/Darwin_64bit" >> $GITHUB_PATH; done
        echo "GULP_LIB=`pwd`/cmd_line/gulp/Libraries" >> $GITHUB_ENV
        echo "PMG_TEST_FILES_DIR=`pwd`/test_files" >> $GITHUB_ENV
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-optional.txt
        pip install -r requirements-dev.txt
        pip install -e .
    - name: pytest
      env:
        PMG_MAPI_KEY: ${{ secrets.PMG_MAPI_KEY }}
        MPLBACKEND: "Agg"
      run: |
        echo "PATH=$PATH"
        pytest pymatgen -rxXs --ignore=pymatgen/analysis --color=yes
